In [1]:
import numpy as np

In [3]:
# np.linspace(start, end, # points)
lsp = np.linspace(0,1,6)
print(lsp)

[ 0.   0.2  0.4  0.6  0.8  1. ]


In [5]:
print(np.ones((4,4)))

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [6]:
print(np.identity(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
# np.arange(start * stop * step)
a = np.arange(4*3*2)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
# review and understand what's happening in each step below!!! 

a = np.arange(12).reshape(3,4)
a[0:3:2,:][:,[0,2]] = 100
a

array([[100,   1, 100,   3],
       [  4,   5,   6,   7],
       [100,   9, 100,  11]])

In [10]:
import pandas as p

In [15]:
list('hijklmop2')[-3:]

['o', 'p', '2']