## Slicing and Broadcasting

In [1]:
import numpy as np

x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])
print(x1.shape)
print(x2.shape)

#print(x1+x2)  # this generate an error
print(x1+x2[:,np.newaxis])
# this flips x2 on its other axis (making it (3,1)), then 
#     broadcasts x2 across all columns and adds elementwise 

(5,)
(3,)
[[ 6  7  8  9 10]
 [ 5  6  7  8  9]
 [ 4  5  6  7  8]]


In [2]:
x2[:,np.newaxis]

array([[5],
       [4],
       [3]])

In [7]:
a1 = np.zeros((4,3)) # with this dimensions a1 can be added with a2
#a1 = np.zeros((3,4))
a2 = np.arange(4)
print(a1.shape)
print(a1)
print(a2.shape)
print(a2)
print('break')
print(a1+a2[:,np.newaxis])

(4, 3)
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
(4,)
[0 1 2 3]
break
[[ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]


notice that a2 is an one-dimensional array where the second dimension is not specified.

the numpy command 
```python
np.newaxis
```
creates a new dimension

In [ ]:
a1 = np.zeros((4,3))
a1[:]=a2[:,np.newaxis]
print(a1.shape)
print(a1)

In [ ]:
a1 = np.zeros((4,3))
a1[:2]=[[-44],[33]]
print(a1)

In [ ]:
a3 = a1[1:3]
print(a3.shape)
print(a3)

In [ ]:
#a3 = a1 # a3 and a1 reference to the same content
a3 = a1[:]  # the content of a1 is copied to a3
print(a3 is a1)
print(id(a1))
print(id(a3))

Different array objects can share the same data using the command "view"

In [ ]:
a4 = a1.view()
print(a4 is a1)
print(a4.base is a1)    # a4 is a view of the data owned by a1

print('The shapes are the same')
print(a1.shape)
print(a4.shape)

print('The shape of a4 is changed')
a4.shape = 2,6
print(a1.shape)        # changing the shape of a4 does not affect a1
print(a4.shape)
print(a4)

In [ ]:
a5 = a1[[1,3,3]]  # copy particular rows to a new array
print('a5: ',a5)

a6 = a5[[1,0],[0,2]]  # building an one-dimensional array with the elements (1,0) and (3,1) from a1
print('a6: ',a6)

In [ ]:
a = np.arange(5)
print(a)
a[[0, 1, 2]] = [1, 2, 3] # we can change specific entries. 
# a[[0, 0, 2]] = [1, 2, 3] # The assignment with index repetition follows the order
print(a)

## Interacting over Arrays and Operations

In [8]:
b = np.arange(16).reshape((4,4))
print(b)

for i in b:
    print('i: ',i)  # i corresponds to the rows
    for j in i:
        print(j)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
i:  [0 1 2 3]
0
1
2
3
i:  [4 5 6 7]
4
5
6
7
i:  [ 8  9 10 11]
8
9
10
11
i:  [12 13 14 15]
12
13
14
15


In [22]:
# always specificy the data type when you're creating an np.array 
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
print(a.shape,b.shape,c.shape)
print('dot(a,b): ',np.dot(a,b))
# Notice that the result is an one-dimensional array

b.shape= 1,2
print('b: ',b)
print(a.shape,b.shape,c.shape)
print(np.dot(a,b))

(2, 2) (2,) (2, 2)
dot(a,b):  [  3.  13.]
b:  [[ 2.  3.]]
(2, 2) (1, 2) (2, 2)


ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

## matplotlib

In [ ]:
import matplotlib.pyplot as plt

x = np.linspace(0,1,100)
y = x**2

f1 = plt.plot(x,y)
plt.setp(f1,lw=1, color='r', linestyle='-',alpha=1.0)
plt.show()

In [ ]:
Y = np.zeros((3,100))
Y[0,:] = 1.0+x
Y[1,:] = x**2
Y[2,:] = np.sin(x)

# matplotlib axis info in format of [xmin,xmax,ymin,ymax]
plt.figure(1)
plt.axis([0,1,0,2])
for i in range(3):
    plt.plot(x,Y[i,:])
    
plt.figure(2)
plt.axis([0,1,0,1])
for i in range(3):
    if (i != 0):
        plt.plot(x,Y[i,:])
    
plt.show()

In [ ]:
plt.figure(3)
plt.subplot(1,2,1)
f2 = plt.plot(x,Y[0,:],x,Y[1,:],x,Y[2,:])
plt.legend(('linear','quadratic','sin'),loc=1)
plt.subplot(1,2,2)
plt.plot(x,np.exp(x))
plt.show()